language: python
python:
  - "2.7"
# python3 not supported in OpenLayers2.13.1
#  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl unzip python apache2
install:
- travis_wait ./install-dependencies.sh
script:
- ./build.sh
notifications:
  email:
    on_success: never
    on_failure: never

